import React,{Component} from 'react';

class MiComponente extends Component {
    render(){
        return (
           <React.Fragment>
             <h1>QuickServices</h1>
             <h2>Aplicación web para Freelancers</h2>
             <hr/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   >
           </React.Fragment>

        );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    }
}
export default MiComponente;